-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 11:16:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbferreteria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbferreteria` ;

-- -----------------------------------------------------
-- Schema dbferreteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbferreteria` DEFAULT CHARACTER SET utf8 ;
USE `dbferreteria` ;

-- -----------------------------------------------------
-- Table `dbferreteria`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Users` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Status` TINYINT NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Userscol_UNIQUE` (`Password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `desc_Categoria` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Proveedor` (
  `Id_provedor` INT NOT NULL AUTO_INCREMENT,
  `Nom_proveedor` VARCHAR(45) NOT NULL,
  `Telf_proveedor` INT NOT NULL,
  PRIMARY KEY (`Id_provedor`),
  UNIQUE INDEX `Nom_proveedor_UNIQUE` (`Nom_proveedor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Productos` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Productos` (
  `id_Productos` INT NOT NULL AUTO_INCREMENT,
  `nom_Producto` VARCHAR(45) NOT NULL,
  `Existencia` INT NOT NULL,
  `Desc_Producto` VARCHAR(100) NOT NULL,
  `Valor_Producto` DOUBLE NOT NULL,
  `Marca` VARCHAR(30) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Proveedor_Id_provedor` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`id_Productos`),
  UNIQUE INDEX `idProductos_UNIQUE` (`id_Productos` ASC) VISIBLE,
  UNIQUE INDEX `nom_Producto_UNIQUE` (`nom_Producto` ASC) VISIBLE,
  INDEX `fk_Productos_Categoria_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Productos_Proveedor1_idx` (`Proveedor_Id_provedor` ASC) VISIBLE,
  INDEX `fk_Productos_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `dbferreteria`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Proveedor1`
    FOREIGN KEY (`Proveedor_Id_provedor`)
    REFERENCES `dbferreteria`.`Proveedor` (`Id_provedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `dbferreteria`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Local` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Estado_lc` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `parroquia_Lc` VARCHAR(45) NOT NULL,
  `RIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocal`),
  UNIQUE INDEX `RIF_UNIQUE` (`RIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Datos_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Datos_cliente` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Datos_cliente` (
  `idDatos_cliente` INT NOT NULL,
  `Nom_cliente` VARCHAR(45) NULL,
  `Apellido_cliente` VARCHAR(45) NULL,
  `Apellido2_cliente` VARCHAR(45) NULL,
  `CI` INT NOT NULL,
  `Telf_cliente` VARCHAR(45) NOT NULL,
  `Estado_cl` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `parroquia_cl` VARCHAR(45) NULL,
  PRIMARY KEY (`idDatos_cliente`),
  UNIQUE INDEX `idDatos_cliente_UNIQUE` (`idDatos_cliente` ASC) VISIBLE,
  UNIQUE INDEX `CI_UNIQUE` (`CI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `Nom_empleado` VARCHAR(45) NULL,
  `Apellido_empleado` VARCHAR(45) NULL,
  `Apellido2_empleado` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `Local_idLocal` INT NOT NULL,
  `Datos_cliente_idDatos_cliente` INT NOT NULL,
  PRIMARY KEY (`idEmpleados`),
  UNIQUE INDEX `idEmpleados_UNIQUE` (`idEmpleados` ASC) VISIBLE,
  INDEX `fk_Empleados_Local1_idx` (`Local_idLocal` ASC) VISIBLE,
  INDEX `fk_Empleados_Datos_cliente1_idx` (`Datos_cliente_idDatos_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `dbferreteria`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_Datos_cliente1`
    FOREIGN KEY (`Datos_cliente_idDatos_cliente`)
    REFERENCES `dbferreteria`.`Datos_cliente` (`idDatos_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Venta` DATE NULL,
  `Monto_venta` DOUBLE NOT NULL,
  `Desc_Compra` VARCHAR(100) NULL,
  `cantidad` INT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `dbferreteria`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Productos_Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Productos_Ventas` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Productos_Ventas` (
  `Ventas_idVentas` INT NOT NULL,
  `Productos_id_Productos` INT NOT NULL,
  INDEX `fk_Productos_Ventas_Ventas1_idx` (`Ventas_idVentas` ASC) VISIBLE,
  INDEX `fk_Productos_Ventas_Productos1_idx` (`Productos_id_Productos` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Ventas_Ventas1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `dbferreteria`.`Ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_Ventas_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `dbferreteria`.`Productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbferreteria`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Datos_cliente_idDatos_cliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Datos_cliente1_idx` (`Datos_cliente_idDatos_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Datos_cliente1`
    FOREIGN KEY (`Datos_cliente_idDatos_cliente`)
    REFERENCES `dbferreteria`.`Datos_cliente` (`idDatos_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
