-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 18:23:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ferreteria
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbferreteria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbferreteria` ;

-- -----------------------------------------------------
-- Schema dbferreteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbferreteria` DEFAULT CHARACTER SET utf8mb3 ;
USE `dbferreteria` ;

-- -----------------------------------------------------
-- Table `dbferreteria`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`categoria` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `desc_Categoria` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`idCategoria` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`datos_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`datos_cliente` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`datos_cliente` (
  `idDatos_cliente` INT NOT NULL,
  `Nom_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido2_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `CI` INT NOT NULL,
  `Telf_cliente` VARCHAR(45) NOT NULL,
  `Estado_cl` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `parroquia_cl` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDatos_cliente`),
  UNIQUE INDEX `idDatos_cliente_UNIQUE` (`idDatos_cliente` ASC) VISIBLE,
  UNIQUE INDEX `CI_UNIQUE` (`CI` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`cliente` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`cliente` (
  `idCliente` INT NOT NULL,
  `Datos_cliente_idDatos_cliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Datos_cliente1_idx` (`Datos_cliente_idDatos_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Datos_cliente1`
    FOREIGN KEY (`Datos_cliente_idDatos_cliente`)
    REFERENCES `dbferreteria`.`datos_cliente` (`idDatos_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`local` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Estado_lc` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `parroquia_Lc` VARCHAR(45) NOT NULL,
  `RIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocal`),
  UNIQUE INDEX `RIF_UNIQUE` (`RIF` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`empleados` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`empleados` (
  `idEmpleados` INT NOT NULL AUTO_INCREMENT,
  `Nom_empleado` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido_empleado` VARCHAR(45) NULL DEFAULT NULL,
  `Apellido2_empleado` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Local_idLocal` INT NOT NULL,
  `Datos_cliente_idDatos_cliente` INT NOT NULL,
  PRIMARY KEY (`idEmpleados`),
  UNIQUE INDEX `idEmpleados_UNIQUE` (`idEmpleados` ASC) VISIBLE,
  INDEX `fk_Empleados_Local1_idx` (`Local_idLocal` ASC) VISIBLE,
  INDEX `fk_Empleados_Datos_cliente1_idx` (`Datos_cliente_idDatos_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Datos_cliente1`
    FOREIGN KEY (`Datos_cliente_idDatos_cliente`)
    REFERENCES `dbferreteria`.`datos_cliente` (`idDatos_cliente`),
  CONSTRAINT `fk_Empleados_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `dbferreteria`.`local` (`idLocal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`proveedor` (
  `Id_provedor` INT NOT NULL AUTO_INCREMENT,
  `Nom_proveedor` VARCHAR(45) NOT NULL,
  `Telf_proveedor` INT NOT NULL,
  PRIMARY KEY (`Id_provedor`),
  UNIQUE INDEX `Nom_proveedor_UNIQUE` (`Nom_proveedor` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`users` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(200) NOT NULL,
  `Status` TINYINT NOT NULL DEFAULT '1',
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `Userscol_UNIQUE` (`contrasena` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`ventas` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Venta` DATE NULL DEFAULT NULL,
  `Monto_venta` DOUBLE NOT NULL,
  `Desc_Compra` VARCHAR(100) NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `dbferreteria`.`empleados` (`idEmpleados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`productos` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`productos` (
  `id_Productos` INT NOT NULL AUTO_INCREMENT,
  `nom_Producto` VARCHAR(45) NOT NULL,
  `Existencia` INT NOT NULL,
  `Desc_Producto` VARCHAR(100) NOT NULL,
  `Valor_Producto` DOUBLE NOT NULL,
  `Marca` VARCHAR(30) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Proveedor_Id_provedor` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `ventas_idventas1` INT NOT NULL,
  `productos_idproductos1` INT NOT NULL,
  PRIMARY KEY (`id_Productos`),
  UNIQUE INDEX `idProductos_UNIQUE` (`id_Productos` ASC) VISIBLE,
  UNIQUE INDEX `nom_Producto_UNIQUE` (`nom_Producto` ASC) VISIBLE,
  INDEX `fk_Productos_Categoria_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Productos_Proveedor1_idx` (`Proveedor_Id_provedor` ASC) VISIBLE,
  INDEX `fk_Productos_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_ventas_idventas1_idx` (`ventas_idventas1` ASC) VISIBLE,
  INDEX `fk_productos_idproductos1_idx` (`productos_idproductos1` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `dbferreteria`.`categoria` (`idCategoria`),
  CONSTRAINT `fk_Productos_Proveedor1`
    FOREIGN KEY (`Proveedor_Id_provedor`)
    REFERENCES `dbferreteria`.`proveedor` (`Id_provedor`),
  CONSTRAINT `fk_Productos_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `dbferreteria`.`users` (`idUsers`),
  CONSTRAINT `fk_ventas_idventas1`
    FOREIGN KEY (`ventas_idventas1`)
    REFERENCES `dbferreteria`.`ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_idproductos1`
    FOREIGN KEY (`productos_idproductos1`)
    REFERENCES `dbferreteria`.`productos` (`id_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dbferreteria`.`productos_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbferreteria`.`productos_ventas` ;

CREATE TABLE IF NOT EXISTS `dbferreteria`.`productos_ventas` (
  `Ventas_idVentas` INT NOT NULL,
  `Productos_id_Productos` INT NOT NULL,
  INDEX `fk_Productos_Ventas_Ventas1_idx` (`Ventas_idVentas` ASC) VISIBLE,
  INDEX `fk_Productos_Ventas_Productos1_idx` (`Productos_id_Productos` ASC) VISIBLE,
  CONSTRAINT `fk_Productos_Ventas_Productos1`
    FOREIGN KEY (`Productos_id_Productos`)
    REFERENCES `dbferreteria`.`productos` (`id_Productos`),
  CONSTRAINT `fk_Productos_Ventas_Ventas1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `dbferreteria`.`ventas` (`idVentas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
